# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:pc
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:information

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:water pump structure
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on:
    runs-on: ubuntu-latestcontinuously

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: Check on the computer whether it is correct or not.

      # Runs a single command using the runners shell
      - name: Run a one-lineNext
        run: echoesp2885 board

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
#Measuring soil moisture
